todoproject/todoapp/urls.py
from django.urls import path, include
from . import views
app_name='todoapp'
urlpatterns = [
    path('', views.add, name='add'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),

    # class based generic views path
    path('cbvhome/', views.TaskListView.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.TaskDetailView.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.TaskUpdateView.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskdeleteView.as_view(), name='cbvdelete'),

]

todoproject/todoproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from todoproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

if  settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=256)
    priority = models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

todoproject/todoapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from todoapp.form import TaskForm
from todoapp.models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


# class based generic views
class TaskListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task'
class TaskDetailView(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'

class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail',kwargs={'pk':self.object.id})

class TaskdeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')
# Create your views here.
def add(request):
    task1=Task.objects.all()

    if request.method == "POST":
        name = request.POST.get('name', )
        priority = request.POST.get('priority', )
        date = request.POST.get('date', )

        movie = Task(name=name, priority=priority, date=date)
        movie.save()
    return render(request,'home.html',{'task':task1})
def delete(request, id):
    if request.method=="POST":
        task = Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request, id):
    task=Task.objects.get(id=id)
    form=TaskForm(request.POST or None,instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'f':form,'task':task})

# def detail(request):
#     task=Task.objects.all()
#     return render(request,'detail.html', {'task':task})

todoproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TODO APP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!--<header>-->
<!--    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">-->
<!--      <div class="container-fluid">-->
<!--        <a class="navbar-brand" href="#">-->
<!--          Movies App-->
<!--        </a>-->
<!--      </div>-->
<!--    </nav>-->
<!--</header>-->
{% block body %}
{% endblock %}

</body>
</html>

todoproject/templates/delete.html
<form action="" method="post">
  {% csrf_token %}
  Are you sure is this task is Done<br>
  <input type="submit" value="Yes completed">
</form>

todoproject/templates/detail.html
{% extends 'base.html'%}
{% block body %}

<div class="col-md-6 mb-4 justify-content-center">
    <div class="card shadow-lg">
        <div class="card-body">
            <h5 class="card-title">{{ task.name }}</h5>
            <p class="card-text">Priority: {{ task.priority }}</p>
            <p class="card-text">Date: {{ task.date }}</p>


            <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
            <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>


        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/edit.html
<form action="" method="post">
    {% csrf_token %}
    {{ f.as_p }}<br>
    <input type="submit" value="Submit">
</form>

todoproject/templates/home.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>TODO LISTS</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form action="" method="post" class="p-4 border rounded shadow-lg bg-light">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="taskName" class="form-label">Task Name</label>
                    <input type="text" class="form-control" id="taskName" name="name" placeholder="Enter Task">
                </div>
                <div class="mb-3">
                    <label for="taskPriority" class="form-label">Priority</label>
                    <input type="number" class="form-control" id="taskPriority" name="priority" placeholder="Enter priority">
                </div>
                <div class="mb-3">
                    <label for="taskDate" class="form-label">Date</label>
                    <input type="date" class="form-control" id="date" name="date" placeholder="Enter Date">
                </div>
                <button type="submit" class="btn btn-primary w-100">Submit</button>
            </form>
        </div>
        <!-- Task Display Section -->
        <div class="col-md-6">
            <h1>Task to be Completed</h1>
            <div class="row">
                {% for i in task %}
                <div class="col-md-6 mb-4">
                    <div class="card shadow-lg">
                        <div class="card-body">
                            <h5 class="card-title">{{ i.name }}</h5>
                            <p class="card-text">Priority: {{ i.priority }}</p>
                            <p class="card-text">Date: {{ i.date }}</p>


                        <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                            <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>


                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

todoproject/templates/update.html
{% extends 'base.html'%}
{% block body %}

<div class="card">
    <div class="card-header">
        <div class="cart-title">
            Update Form
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}<br>
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>

</div>
{% endblock %}